@startuml
'https://plantuml.com/sequence-diagram

autonumber

Scheduler -> ConfigurationManager: scanConfiguration()
ConfigurationManager --> "Système de fichier": read file
ConfigurationManager -> ConfigurationManager: create configuration object

ConfigurationManager -> Network: disconnect()
ConfigurationManager -> Network: connect(configuration)

@enduml