@startuml
'https://plantuml.com/sequence-diagram

autonumber

ApplicationLauncher -> ConfigurationManager: getConfiguration
ConfigurationManager -> "Système de fichier": read file
ConfigurationManager -> ConfigurationManager: create configuration object

ConfigurationManager --> ApplicationLauncher: configuration
ApplicationLauncher -> Network: startup (configuration))

@enduml